config/routes.rb
Somervillefoodrescue::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations'}

  root 'pages#index'

  get 'volunteers' => 'pages#users_index', as: :volunteers
  get 'volunteers/:id' => 'pages#show_user', as: :volunteer

  get 'take_shift/:pickup_id' => 'actions#take_shift', as: :take_shift
  get 'leave_shift/:pickup_id' => 'actions#leave_shift', as: :leave_shift
  get 'make_admin/:user_id' => 'actions#make_admin', as: :make_admin
  get 'demote_admin/:user_id' => 'actions#demote_admin', as: :demote_admin

  match 'users/:id' => 'pages#destroy_user', :via => :delete, :as => :admin_destroy_user

  mount PostgresqlLoStreamer::Engine => "/user_avatar"
  resources :donors
  resources :recipients
  resources :pickups, except: ["show"]
  resources :pickup_reports, path: :reports

end

app/models/donor.rb
# == Schema Information
#
# Table name: donors
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  address      :string(255)
#  email        :string(255)
#  phone_number :string(255)
#  instructions :text
#  created_at   :datetime
#  updated_at   :datetime
#

class Donor < ActiveRecord::Base
	has_many :pickups
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
	
	def index
		@donors = Donor.all.order('created_at ASC')
	end

	def show
		@donor = Donor.find(params[:id])
	end

	def new
		@donor = Donor.new
	end

	def create
		@donor = Donor.create(donor_params)

		redirect_to action: :index
	end

	def edit
		@donor = Donor.find(params[:id])
	end

	def update
		@donor = Donor.find(params[:id])
		@donor.update_attributes(donor_params)

		redirect_to action: :index
	end

	def destroy
		@donor = Donor.find(params[:id])
		@donor.destroy

		@pickups_for_donor = Pickup.where(donor_id: @donor.id)
		@pickups_for_donor.destroy_all

		redirect_to action: :index
	end

	private

	def donor_params
		params.require(:donor).permit(:name, :address, :email, :phone_number, :instructions)
	end

end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/donors/edit.html.haml
#call.background
	.container.white-text
		.row
			.col-md-12
				%h1
					Edit Donor: 
					= @donor.name
		.row.spacer
		= form_for @donor do |f|
			.row.text-left
				.col-md-2
				.col-md-8
					.row
						.col-md-12
							%h3 Name:
							= f.text_field :name, class: "form-control"
					.row
						.col-md-12
							%h3 Address:
							= f.text_field :address, class: "form-control"
					.row
						.col-md-12
							%h3 Email:
							= f.email_field :email, class: "form-control"
					.row
						.col-md-12
							%h3 Phone Number (No Punctuation):
							= f.text_field :phone_number, class: "form-control"
					.row
						.col-md-12
							%h3 Instructions:
							= f.text_area :instructions, style: "height: 300px;", class: "form-control"
					.row
						.col-md-12
							%br/
							= f.submit "Edit Donor", class: 'btn btn-success btn-lg'
				.col-md-2

app/views/donors/index.html.haml
#call.background
	.container
		.row
			.col-md-12.centered
				%h1.underlined
					DONORS
				.spacer
		- @donors.all.each do |donor|
			.row
				.col-md-12.donor-box
					.left-section
						.donor-name
							= link_to donor_path(donor.id) do
								= donor.name
						.donor-address
							= donor.address
						&nbsp;
						&nbsp;
						&bull;
						&nbsp;
						&nbsp;
						.donor-phone
							= number_to_phone(donor.phone_number, area_code: true)
					.right-section
						= mail_to donor.email, class: "btn btn-primary btn-lg donor-button" do
							%i.fa.fa-envelope
							&nbsp;
							Email
						- if user_signed_in?
							- if current_user.admin?
								= link_to edit_donor_path(donor), class: "btn btn-warning btn-lg donor-button" do
									%i.fa.fa-pencil
									&nbsp;
									Edit
								= link_to donor_path(donor), method: :delete, data: { confirm: "Are you sure you want to delete this donor?" }, class: "btn btn-danger btn-lg donor-button" do
									%i.fa.fa-minus-circle
									&nbsp;
									Delete
		- if user_signed_in?
			- if current_user.admin?
				.row
					= link_to new_donor_path, class: "btn btn-success btn-lg donor-button col-md-12" do
						%i.fa.fa-plus
						&nbsp;
						New Donor

app/views/donors/new.html.haml
#call.background
	.container.white-text
		.row
			.col-md-12
				%h1 Create a New Donor
		.row.spacer
		= form_for @donor do |f|
			.row.text-left
				.col-md-2
				.col-md-8
					.row
						.col-md-12
							%h3 Name:
							= f.text_field :name, class: "form-control"
					.row
						.col-md-12
							%h3 Address:
							= f.text_field :address, class: "form-control"
					.row
						.col-md-12
							%h3 Email:
							= f.email_field :email, class: "form-control"
					.row
						.col-md-12
							%h3 Phone Number (No Punctuation):
							= f.text_field :phone_number, class: "form-control"
					.row
						.col-md-12
							%h3 Instructions:
							= f.text_area :instructions, style: "height: 300px;", class: "form-control"
					.row
						.col-md-12
							%br/
							= f.submit "Create Donor", class: 'btn btn-success btn-lg'
				.col-md-2

app/views/donors/show.html.haml
#call.background
	.container
		.row
			.col-md-12.centered
				%h1.underlined
					= @donor.name.upcase
				.spacer
		.row
			.col-md-12.volunteer-profile-box
				.row
					.col-md-12.text-left
						%h2
							Contact Information
						%hr
				.row
					.col-md-12.text-left
						%h4
							%i.fa.fa-envelope
							&nbsp;
							= mail_to @donor.email
				.row
					.col-md-12.text-left
						%h4
							%i.fa.fa-phone
							&nbsp;
							= number_to_phone(@donor.phone_number, area_code: true)
				.row.spacer
		.row
			.col-md-12.volunteer-profile-box
				.row
					.col-md-12.text-left
						%h2
							Pickup Instructions
						%hr
				.row
					.col-md-12.text-left
						%h5
							= @donor.instructions
				.row.spacer
		.row
			.col-md-12.volunteer-profile-box
				.row
					.col-md-12.text-left
						%h2
							Registered Donations
						%hr
					.col-md-12.text-left#volunteer-shift-holder
						- if Pickup.where(donor_id: @donor.id).count > 0
							%h4.day_of_week Monday
							- Pickup.where(donor_id: @donor.id, day_of_week: "Monday").each do |pickup|
								= render 'partials/pickup_box', pickup: pickup
							.spacer
							%h4.day_of_week Tuesday
							- Pickup.where(donor_id: @donor.id, day_of_week: "Tuesday").each do |pickup|
								= render 'partials/pickup_box', pickup: pickup
							.spacer
							%h4.day_of_week Wednesday
							- Pickup.where(donor_id: @donor.id, day_of_week: "Wednesday").each do |pickup|
								= render 'partials/pickup_box', pickup: pickup
							.spacer
							%h4.day_of_week Thursday
							- Pickup.where(donor_id: @donor.id, day_of_week: "Thursday").each do |pickup|
								= render 'partials/pickup_box', pickup: pickup
							.spacer
							%h4.day_of_week Friday
							- Pickup.where(donor_id: @donor.id, day_of_week: "Friday").each do |pickup|
								= render 'partials/pickup_box', pickup: pickup
							.spacer
							%h4.day_of_week Saturday
							- Pickup.where(donor_id: @donor.id, day_of_week: "Saturday").each do |pickup|
								= render 'partials/pickup_box', pickup: pickup
							.spacer
							%h4.day_of_week Sunday
							- Pickup.where(donor_id: @donor.id, day_of_week: "Sunday").each do |pickup|
								= render 'partials/pickup_box', pickup: pickup
						- else
							%h4
								%i None
				.row.spacer