config/routes.rb
Somervillefoodrescue::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations'}

  root 'pages#index'

  get 'volunteers' => 'pages#users_index', as: :volunteers
  get 'volunteers/:id' => 'pages#show_user', as: :volunteer

  get 'take_shift/:pickup_id' => 'actions#take_shift', as: :take_shift
  get 'leave_shift/:pickup_id' => 'actions#leave_shift', as: :leave_shift
  get 'make_admin/:user_id' => 'actions#make_admin', as: :make_admin
  get 'demote_admin/:user_id' => 'actions#demote_admin', as: :demote_admin

  match 'users/:id' => 'pages#destroy_user', :via => :delete, :as => :admin_destroy_user

  mount PostgresqlLoStreamer::Engine => "/user_avatar"
  resources :donors
  resources :recipients
  resources :pickups, except: ["show"]
  resources :pickup_reports, path: :reports

end

app/views/partials/_authentication_modals.html.haml
#signIn.modal.fade
    .modal-dialog
        .modal-content
            .modal-header
                %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
                %h3.modal-title Sign In
            .modal-body
                = form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f|
                    = devise_error_messages!
                    %br/
                    .left-inner-addon
                        %i.fa.fa-envelope
                        = f.text_field :email, :placeholder => "Email", :autofocus => true, class: "form-control"
                    %br/
                    .left-inner-addon
                        %i.fa.fa-asterisk
                        = f.password_field :password, :placeholder => "Password", class: "form-control"
                    %br/
                    - if devise_mapping.rememberable?
                        %label
                            = f.check_box :remember_me
                            Remember Me
                    %br/
                    %br/
                    = f.submit "Sign In", class: "btn btn-success btn-lg"
#signUp.modal.fade
    .modal-dialog
        .modal-content
            .modal-header
                %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
                %h3.modal-title Become A Volunteer
            .modal-body
                = form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f|
                    = devise_error_messages!
                    .left-inner-addon
                        %i.fa.fa-user
                        = f.text_field :full_name, :placeholder => "Full Name", :autofocus => true, class: "form-control"
                    %br/
                    .left-inner-addon
                        %i.fa.fa-envelope
                        = f.email_field :email, :placeholder => "Email", class: "form-control"
                    %br/
                    .left-inner-addon
                        %i.fa.fa-phone
                        = f.text_field :phone_number, :placeholder => "Phone Number", class: "form-control"
                    %br/
                    .left-inner-addon
                        %i.fa.fa-asterisk
                        = f.password_field :password, :placeholder => "Password", class: "form-control"
                    %br/
                    .left-inner-addon
                        %i.fa.fa-asterisk
                        = f.password_field :password_confirmation, :placeholder => "Password Confirmation", class: "form-control"
                    %br/
                    %span.btn.btn-default.btn-file.form-control
                        #file-name
                            %i.fa.fa-camera
                            &nbsp;
                            Add Profile Picture
                        = f.file_field :avatar
                    %br/
                    %br/
                    %br/
                    = f.submit "Sign Up", class: "btn btn-success btn-lg"

app/views/partials/_navbar.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
	.container-fluid
		.navbar-header
			%button.navbar-toggle{"data-target" => "#collapse", "data-toggle" => "collapse", type: "button"}
				%span.sr-only Toggle navigation
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
			.navbar-brand
				= link_to "Tufts Food Rescue", root_url
		.collapse.navbar-collapse#collapse
			%ul.nav.navbar-nav
				%li
					= link_to "Pickups", pickups_path
				%li
					= link_to "Donors", donors_path
				%li
					= link_to "Recipients", recipients_path
				%li
					= link_to "Volunteers", volunteers_path
				%li
					= link_to "Reports", pickup_reports_path
			
			%ul.nav.navbar-nav.navbar-right
				- if user_signed_in?
					%li
						= link_to "Sign Out", destroy_user_session_path, :method => :delete
				- else
					%li
						= link_to "Sign In", "#signIn", "data-toggle" => "modal"
					%li
						= link_to "Sign Up", "#signUp", "data-toggle" => "modal"

app/views/partials/_pickup_box.html.haml
- @donor = Donor.find(pickup.donor_id)
- @recipient = Recipient.find(pickup.recipient_id)
.row
	.col-md-12.pickup-box
		.left-section.centered.left-section-width
			.row
				.col-md-4
					%h4 DONOR
					.div
						= link_to donor_path(@donor.id) do
							= truncate(@donor.name, length: 22)
					.div
						= "(#{pickup.donor_window_start.strftime('%I:%M %p')} - #{pickup.donor_window_end.strftime('%I:%M %p')})"
				.col-md-1
					%h4
						%i.fa.fa-arrow-right
				.col-md-4
					%h4 RECIPIENT
					.div
						= link_to recipient_path(@recipient.id) do
							= truncate(@recipient.name, length: 22)
					.div
						= "(#{pickup.recipient_window_start.strftime('%I:%M %p')} - #{pickup.recipient_window_end.strftime('%I:%M %p')})"
				.col-md-3
					%h4 VOLUNTEER
					.div
						- if pickup.user_id.nil?
							%i No Volunteer
						- else
							= link_to volunteer_path(pickup.user_id) do
								= truncate(User.find(pickup.user_id).full_name, length: 15)
					.div
						- if !pickup.user_id.nil?
							= number_to_phone(User.find(pickup.user_id).phone_number, area_code: true)
		.right-section
			- if user_signed_in?
				- if pickup.user_id.nil?
					= link_to take_shift_path(pickup.id), class: "btn btn-success btn-lg pickup-button" do
						%i.fa.fa-clock-o
						&nbsp;
						Take Shift
				- if pickup.user_id == current_user.id
					= link_to new_pickup_report_path(donor_id: @donor.id, recipient_id: @recipient.id, pickup_id: pickup.id), class: "btn btn-success btn-lg pickup-button" do
						%i.fa.fa-plus
						&nbsp;
						New Report
					= link_to leave_shift_path(pickup.id), class: "btn btn-warning btn-lg pickup-button" do
						%i.fa.fa-arrow-circle-right
						&nbsp;
						Leave Shift
				- if current_user.admin?
					= link_to edit_pickup_path(id: pickup.id, donor: pickup.donor_id, recipient: pickup.recipient_id, day_of_week: pickup.day_of_week), class: "btn btn-primary btn-lg pickup-button" do
						%i.fa.fa-pencil
						&nbsp;
						Edit
					= link_to pickup_path(pickup), method: :delete, data: { confirm: "Are you sure you want to delete this pickup?" }, class: "btn btn-danger btn-lg pickup-button" do
						%i.fa.fa-minus-circle
						&nbsp;
						Delete

app/views/partials/_pickup_report_box.html.haml
- pickup = Pickup.find(pickup_report.pickup_id)
- @donor = Donor.find(pickup.donor_id)
- @recipient = Recipient.find(pickup.recipient_id)
.row
	.col-md-12.pickup-box
		.row
			.col-md-1
				%h4
					%u DATE
				.div
					= pickup_report.created_at.strftime('%m/%d/%y')
			.col-md-2
				%h4
					%u DONOR
				.div
					= link_to donor_path(@donor.id) do
						= truncate(@donor.name, length: 22)
				.div
					= "(#{pickup.donor_window_start.strftime('%I:%M %p')} - #{pickup.donor_window_end.strftime('%I:%M %p')})"
			.col-md-1
				%h4
					%i.fa.fa-arrow-right.full-width.centered-text
			.col-md-2
				%h4
					%u RECIPIENT
				.div
					= link_to recipient_path(@recipient.id) do
						= truncate(@recipient.name, length: 22)
				.div
					= "(#{pickup.recipient_window_start.strftime('%I:%M %p')} - #{pickup.recipient_window_end.strftime('%I:%M %p')})"
		.row.spacer
		.row
			.col-md-2
				%h4
					%u PRODUCE
				.div
					= pickup_report.produce_weight
					Pounds
			.col-md-2
				%h4
					%u DAIRY
				.div
					= pickup_report.dairy_weight
					Pounds
			.col-md-2
				%h4
					%u MEAT
				.div
					= pickup_report.meat_weight
					Pounds
			.col-md-2
				%h4
					%u BREAD
				.div
					= pickup_report.bread_weight
					Pounds
			.col-md-2
				%h4
					%u OTHER
				.div
					= pickup_report.other_weight
					Pounds
			.col-md-2
				%h4
					%u TOTAL
				.div
					= pickup_report.produce_weight + pickup_report.dairy_weight + pickup_report.meat_weight + pickup_report.bread_weight + pickup_report.other_weight
					Pounds
		.row.spacer
		.row
			.col-md-4
				- if current_user.admin?
					= link_to pickup_report_path(pickup_report), method: :delete, data: { confirm: "Are you sure you want to delete this pickup report?" }, class: "btn btn-danger btn-lg pickup-button" do
						%i.fa.fa-minus-circle
						&nbsp;
						Delete