config/routes.rb
Somervillefoodrescue::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations'}

  root 'pages#index'

  get 'volunteers' => 'pages#users_index', as: :volunteers
  get 'volunteers/:id' => 'pages#show_user', as: :volunteer

  get 'take_shift/:pickup_id' => 'actions#take_shift', as: :take_shift
  get 'leave_shift/:pickup_id' => 'actions#leave_shift', as: :leave_shift
  get 'make_admin/:user_id' => 'actions#make_admin', as: :make_admin
  get 'demote_admin/:user_id' => 'actions#demote_admin', as: :demote_admin

  match 'users/:id' => 'pages#destroy_user', :via => :delete, :as => :admin_destroy_user

  mount PostgresqlLoStreamer::Engine => "/user_avatar"
  resources :donors
  resources :recipients
  resources :pickups, except: ["show"]
  resources :pickup_reports, path: :reports

end

app/views/pages/index.html.haml
#headerwrap
    .container
        .row.spacer
            .col-lg-12
                %h1.h1-title-shwopp TUFTS FOOD RESCUE
        .row
            .col-lg-12
                %i
                    %h3
                        Since November 8th, 2014 TFR has rescued the following amounts of food from going to waste:
        .row.spacer
            .col-sm-2
                %h4
                    %u
                        PRODUCE
                %h3
                    = "#{@produce_weight} lbs."
            .col-sm-2
                %h4
                    %u
                        DAIRY
                %h3
                    = "#{@dairy_weight} lbs."
            .col-sm-2
                %h4
                    %u
                        MEAT
                %h3
                    = "#{@meat_weight} lbs."
            .col-sm-2
                %h4
                    %u
                        BREAD
                %h3
                    = "#{@bread_weight} lbs."
            .col-sm-2
                %h4
                    %u
                        OTHER
                %h3
                    = "#{@other_weight} lbs."
            .col-sm-2
                %h4
                    %u
                        TOTAL
                %h3
                    = "#{@total_weight} lbs."
        .row.spacer
            .col-lg-12
                %i.fa.fa-angle-down
#call
    .container
        .row
            %h3 WHAT IS TUFTS FOOD RESCUE?
            .col-lg-8.col-lg-offset-2
                %p Tufts Food Rescue works to create and ensure food security in the local communities (Somerville and Medford) surrounding Tufts. We run a food collection network involving numerous donors and recipients, ranging from farmers markets and grocery stores to homeless shelters and food pantries. We collect food that would otherwise be thrown away  (despite its good condition) and deliver it to our partner recipients. These recipients in turn provide individuals and households in need with fresh options as a supplement as a complement to the low nutrient high calorie diet characteristic of low-income diets.
                %br/
                - if !user_signed_in?
                    %p
                        = link_to "Sign In Now", "#signIn", class: "btn btn-warning btn-lg", "data-toggle" => "modal"
                        = link_to "Become A Volunteer", "#signUp", class: "btn btn-green btn-lg", "data-toggle" => "modal"
        .row
            .col-md-2
            .col-md-8
                / .main-chart
            .col-md-2

app/views/pages/show_user.html.haml
#call.background
	.container
		.row
			.col-md-12.centered
				%h1.underlined
					= @user.full_name.upcase
				.spacer
		.row
			.col-md-12.volunteer-profile-box
				.row
					.col-md-12.text-left
						%h2
							Contact Information
						%hr
				.row
					.col-md-12.text-left
						%h4
							%i.fa.fa-envelope
							&nbsp;
							= mail_to @user.email
				.row
					.col-md-12.text-left
						%h4
							%i.fa.fa-phone
							&nbsp;
							= number_to_phone(@user.phone_number, area_code: true)
				.row.spacer
		.row
			.col-md-12.volunteer-profile-box
				.row
					.col-md-12.text-left
						%h2
							Registered Donations
						%hr
					.col-md-12.text-left#volunteer-shift-holder
						- if Pickup.where(user_id: @user.id).count > 0
							%h4.day_of_week Monday
							- Pickup.where(user_id: @user.id, day_of_week: "Monday").each do |pickup|
								= render 'partials/pickup_box', pickup: pickup
							.spacer
							%h4.day_of_week Tuesday
							- Pickup.where(user_id: @user.id, day_of_week: "Tuesday").each do |pickup|
								= render 'partials/pickup_box', pickup: pickup
							.spacer
							%h4.day_of_week Wednesday
							- Pickup.where(user_id: @user.id, day_of_week: "Wednesday").each do |pickup|
								= render 'partials/pickup_box', pickup: pickup
							.spacer
							%h4.day_of_week Thursday
							- Pickup.where(user_id: @user.id, day_of_week: "Thursday").each do |pickup|
								= render 'partials/pickup_box', pickup: pickup
							.spacer
							%h4.day_of_week Friday
							- Pickup.where(user_id: @user.id, day_of_week: "Friday").each do |pickup|
								= render 'partials/pickup_box', pickup: pickup
							.spacer
							%h4.day_of_week Saturday
							- Pickup.where(user_id: @user.id, day_of_week: "Saturday").each do |pickup|
								= render 'partials/pickup_box', pickup: pickup
							.spacer
							%h4.day_of_week Sunday
							- Pickup.where(user_id: @user.id, day_of_week: "Sunday").each do |pickup|
								= render 'partials/pickup_box', pickup: pickup
						- else
							%h4
								%i None
				.row.spacer
		.row
			.col-md-12.volunteer-profile-box
				.row
					.col-md-12.text-left
						%h2
							Pickup Statistics
						%hr

app/views/pages/users_index.html.haml
#call.background
	.container
		.row
			.col-md-12.centered
				%h1.underlined
					VOLUNTEERS
				.spacer
		- @users.all.each do |user|
			.row
				.col-md-12.volunteer-box
					.left-section
						.volunteer-info
							.volunteer-name
								= link_to volunteer_path(user.id) do
									= user.full_name
							.volunteer-phone
								= number_to_phone(user.phone_number, area_code: true)
					.right-section
						= mail_to user.email, class: "btn btn-primary btn-lg volunteer-button" do
							%i.fa.fa-envelope
							&nbsp;
							Email
						/ = link_to volunteer_path(user.id), class: "btn btn-warning btn-lg volunteer-button" do
						/ 	%i.fa.fa-bar-chart-o
						/ 	&nbsp;
						/ 	Stats
						- if user_signed_in?
							- if current_user.admin?
								- if !user.admin?
									= link_to make_admin_path(user.id), class: "btn btn-success btn-lg volunteer-button" do
										%i.fa.fa-arrow-circle-up
										&nbsp;
										Make Admin
								- else
									= link_to demote_admin_path(user.id), class: "btn btn-default btn-lg volunteer-button" do
										%i.fa.fa-arrow-circle-down
										&nbsp;
										Demote Admin
								= link_to admin_destroy_user_path(user.id), method: :delete, confirm: 'Are you sure?', class: "btn btn-danger btn-lg volunteer-button" do
									%i.fa.fa-minus-circle
									&nbsp;
									Delete